//Global Mults
#define PROJ_DAM_MULT 1.2

//Marine Mults
#define MARINE_BASE_SLOWDOWN_MULT 1.1
#define SHOTGUN_DAMAGE_MULT 0.8
#define SMG_DAMAGE_MULT 0.8

// Xeno Mults
#define XENO_MELEE_DAM_MULT 1.2
#define XENO_HEALTH_MULT 1.4
#define XENO_SPEED_MULT -0.1
#define XENO_ACID_DAM_MULT 1.05
#define XENO_BOMB_STRENGTH_MULT 1.2