//Global Mults
#define PROJ_DAM_MULT 2
#define PROJ_PEN_MULT 2
#define GLOBAL_MOVEMENT_SPEED 125

//Marine Mults
#define MARINE_BASE_SLOWDOWN_MULT 0.9
#define REQ_COST_MULT 0.8
#define BARRICADE_HEALTH_MULT 2.1
#define BARRICADE_BUILDING_TIME_MULT 1.15
#define SHOTGUN_DAMAGE_MULT 1.1
#define SMG_DAMAGE_MULT 1.1
#define RIFLE_DAMAGE_MULT 1.1
#define SPECIALIST_DAMAGE_MULT 1.1
#define SENTRY_DAMAGE_MULT 0.9
#define REVOLVER_DAMAGE_MULT 1.1
#define PISTOL_DAMAGE_MULT 1.1
#define MOUNTED_DAMAGE_MULT 1.1
#define LAUNCHER_DAMAGE_MULT 1.1
#define EXPLOSIVE_DAMAGE_MULT 2
#define FLAMER_DAMAGE_MULT 2
#define FIRE_DAMAGE_MULT 2
#define ENERGY_DAMAGE_MULT 1.1
#define MELEE_DAMAGE_MULT 2
#define WIELD_DELAY_MULT 0.5
#define AIM_SLOWDOWN_MULT 0.5
#define SNIPER_LASER_PEN_MULT 2
#define PROJ_INCENDIARY_FIRE_STACK_MULT 2

// Xeno Mults
#define XENO_MELEE_DAM_MULT 2
#define XENO_HEALTH_MULT 1
#define XENO_SPEED_MULT 0.9
#define ACID_SPIT_DAM_MULT 2
#define SPIT_DELAY_MULT 2
#define XENO_ACID_SPRAY_DAM_MULT 1
#define XENO_BOMB_STRENGTH_MULT 1
#define XENO_ABILITY_COOLDOWN 0.5
#define XENO_BLESSING_COST 0.8
#define XENO_EVO_MULT 0.8
#define XENO_UPG_MULT 0.01
#define XENO_PLASMA_MULT 0.8
#define XENO_PLASMA_GAIN_MULT 1.2
#define XENO_PLASMA_COST = 2
#define XENO_NPC_HEALTH_MULT 1
#define XENO_BUILD_TIME_MULT 0.75
#define XENO_PLASMA_COST 2